# Generated by Django 5.0.4 on 2024-11-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
